
GET http://localhost:3000/api/v1/estados
###
GET http://localhost:3000/api/v1/estados/4

###
POST http://localhost:3000/api/v1/estados
Content-Type: application/json
sss
{
    "estado": "Espirito Santo",
    "uf" : "ES"
}


###
PUT http://localhost:3000/api/v1/estados/1
Content-Type: application/json

{
    "estado": "Sao Paulo",
    "uf" : "SP"
}

###
DELETE http://localhost:3000/api/v1/estados/1
