
GET http://localhost:3000/api/estados
###
GET http://localhost:3000/api/estados/1

###
POST http://localhost:3000/api/estados
Content-Type: application/json

{
    "estado": "São Paulo",
    "uf" : "SP"
}


###
PUT http://localhost:3000/api/estados/1
Content-Type: application/json

{
    estado: "São Paulo",
    uf : "SP"
}

###
DELETE http://localhost:3000/api/estados/1
