### Variáveis Globais
@baseUrl = http://localhost:3600/api
@username = teste login
@password = teste123

@idtest = 2

### 1. Criar um novo usuário (Sign Up)
POST {{baseUrl}}/users
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### 2. Realizar Login (Gera o Token JWT)
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### Armazenar o token da resposta acima
@authToken = {{login.response.body.token}}

### 3. Listar Usuários (Rota Protegida)
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/users

### 4. Deletar um Usuário (Troque o ID pelo desejado)
DELETE {{baseUrl}}/users/{{idtest}}
Authorization: Bearer {{authToken}}

### 5. update um Usuário (Troque o ID pelo desejado)
PUT {{baseUrl}}/users/{{idtest}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "username": "Maria Oliveira",
    "password": "{{password}}"
}

### 6. GETBYID um Usuário (Busca o ID pelo desejado)
GET {{baseUrl}}/users/{{idtest}}
Authorization: Bearer {{authToken}}